image: gcc

build:
  stage: build

  before_script:
    - apt update && apt -y install make autoconf
  script:
    - g++ -Wall -O2 class.cpp -o class
    - cc -Wall -O2 client.c -o client
    - cc -Wall -O2 coffee.c -o coffee
    - g++ -Wall -O2 copy.cpp -o copy
    - g++ -Wall -O2 cstring.cpp -o cstring
    - cc -Wall -O2 curses.c -lncurses -o curses
    - cc -Wall -O2 digits.c -o digits
    - cc -Wall -O2 echo.c -o echo
    - cc -Wall -O2 evensodds.c -o evensodds
    - cc -Wall -O2 fork.c -o fork
    - cc -Wall -O2 func.c -o func
    - cc -Wall -O2 funcpointer.c -o funcpointer
    - cc -Wall -O2 head.c -o head
    - g++ -Wall -O2 inherit.cpp -o inherit
    - cc -Wall -O2 linklist.c -o linklist
    - cc -Wall -O2 linkpop.c -o linkpop
    - cc -Wall -O2 linkpush.c -o linkpush
    - cc -Wall -O2 loops.c -o loops
    - cc -Wall -O2 ls.c -o ls
    - cc -Wall -O2 malloc.c -o malloc
    - cc -Wall -O2 multiserver.c -o multiserver
    - cc -Wall -O2 outfx.c -o outfx
  artifacts:
    paths:
      - class
      - client
      - coffee
      - copy
      - cstring
      - curses
      - digits
      - echo
      - evensodds
      - fork
      - func
      - funcpointer
      - head
      - inherit
      - linklist
      - linkpop
      - linkpush
      - loops
      - ls
      - malloc
      - multiserver
      - outfx
  cache:
    paths:
      - "*.o"
      - evens
      - odds

# run tests using the binary built before
test:
  stage: test
  script:
    - ./class
    - echo 5 | ./coffee
    - ./copy copy.cpp shit.txt
    - ./cstring
    - echo "fuck29" | ./digits

