name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Dependencies
      run: sudo apt-get install -y libx11-dev libx11-xcb-dev libxft-dev libxcb-util0-dev
    - name: Build
      run: |
        g++ -Wall -O2 etc/class.cpp -o etc/class
        cc -Wall -O2 etc/curses.c -lncurses -o etc/curses
        cc -Wall -O2 etc/func.c -o etc/func
        cc -Wall -O2 etc/getch.c -lncurses -o etc/getch
        g++ -Wall -O2 etc/inherit.cpp -o etc/inherit
        cc -Wall -O2 etc/invert.c -o etc/invert
        cc -Wall -O2 etc/outfx.c -o etc/outfx
        cc -Wall -O2 etc/password.c -lncurses -o etc/password
        cc -Wall -O2 etc/window.c -lncurses -o etc/window
        cc -Wall -O2 io/cat.c -o io/cat
        cc -Wall -O2 io/cat2.c -o io/cat2

