name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Dependencies
      run: sudo apt-get install -y libx11-dev libx11-xcb-dev libxft-dev libxcb-util0-dev
    - name: Build
      run: |
        g++ -Wall -O2 etc/class.cpp -o etc/class
        cc -Wall -O2 etc/curses.c -lncurses -o etc/curses
        cc -Wall -O2 etc/func.c -o etc/func
        cc -Wall -O2 etc/getch.c -lncurses -o etc/getch
        g++ -Wall -O2 etc/inherit.cpp -o etc/inherit
        cc -Wall -O2 etc/invert.c -o etc/invert
        cc -Wall -O2 etc/outfx.c -o etc/outfx
        cc -Wall -O2 etc/password.c -lncurses -o etc/password
        cc -Wall -O2 etc/window.c -lncurses -o etc/window
        cc -Wall -O2 io/cat.c -o io/cat
        cc -Wall -O2 io/cat2.c -o io/cat2
        cc -Wall -O2 io/coffee.c -o io/coffee
        g++ -Wall -O2 io/copy.cpp -o io/copy
        g++ -Wall -O2 io/cstring.cpp -o io/cstring
        cc -Wall -O2 io/digits.c -o io/digits
        cc -Wall -O2 io/echo.c -o io/echo
        g++ -Wall -O2 io/echo.cpp -o io/echo2
        cc -Wall -O2 io/evensodds.c -o io/evensodds
        cc -Wall -O2 io/head.c -o io/head
        cc -Wall -O2 io/loops.c -o io/loops
        g++ -Wall -O2 io/minmax.cpp -o io/minmax
        cc -Wall -O2 io/racecar.c -o io/racecar
        cc -Wall -O2 io/read.c -o io/read
        g++ -Wall -O2 io/read.cpp -o io/read2
        cc -Wall -O2 io/size.c -o io/size
        cc -Wall -O2 io/spaces.c -o io/spaces
        cc -Wall -O2 io/strings.c -o io/strings
        cc -Wall -O2 io/write.c -o io/write
        g++ -Wall -O2 io/write.cpp -o io/write2
        cc -Wall -O2 network/client.c -o network/client
        cc -Wall -O2 network/hostname.c -o network/hostname
        cc -Wall -O2 network/http.c -o network/http
        cc -Wall -O2 network/multiserver.c -o network/multiserver
        cc -Wall -O2 network/server.c -o network/server
        cc -Wall -O2 point/bitfield.c -o point/bitfield
        cc -Wall -O2 point/funcpointer.c -o point/funcpointer
        cc -Wall -O2 point/linklist.c -o point/linklist
        cc -Wall -O2 point/linkpop.c -o point/linkpop
        cc -Wall -O2 point/linkpush.c -o point/linkpush
        cc -Wall -O2 point/malloc.c -o point/malloc
        cc -Wall -O2 point/realloc.c -o point/realloc
        cc -Wall -O2 point/structfunc.c -o point/structfunc
        cc -Wall -O2 point/union.c -o point/union
        cc -Wall -O2 point/hashmap.c -o point/hashmap
        cc -Wall -O2 point/hashtable.c -o point/hashtable
        cc -Wall -O2 sys/daemon.c -o sys/daemon
        cc -Wall -O2 sys/fork.c -o sys/fork
        cc -Wall -O2 sys/ls.c -o sys/ls
        cc -Wall -O2 sys/pid.c -o sys/pid
        cc -Wall -O2 sys/pipe.c -o sys/pipe
        cc -Wall -O2 sys/shell.c -o sys/shell
        cc -Wall -O2 sys/speak.c -o sys/speak
        cc -Wall -O2 sys/symlink.c -o sys/symlink
        cc -Wall -O2 sys/tick.c -o sys/tick
        cc -Wall -O2 thread/condsignal.c -lpthread -o thread/condsignal
        cc -Wall -O2 thread/mutex.c -lpthread -o thread/mutex
        g++ -Wall -O2 -pthread -std=c++11 thread/mutex.cpp -o thread/mutex2
        g++ -Wall -O2 -pthread thread/thread.cpp -o thread/thread
        cc -Wall -O2 thread/threads.c -lpthread -o thread/threads
        cc -Wall -O2 x/events.c -L/usr/X11/lib -lxcb -o x/events
        cc -Wall -O2 x/fc.c -lfontconfig -o x/fc
        cc -Wall -O2 x/xft.c -lX11 -lXft -lfreetype -I/usr/include/freetype2 -o x/xft
        cc -Wall -O2 x/xhello.c -L/usr/X11/lib -lX11 -o x/xhello
        cc -Wall -O2 x/xkeys.c -L/usr/X11/lib -lX11 -o x/xkeys
        cc -Wall -O2 x/xresource.c -L/usr/X11/lib -lX11 -o x/xresource
        g++ -Wall -O2 time.cpp -o time
        cc -Wall -O2 bits.c -o bits
